name: books_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pandas=1.5.3
  - numpy=1.23.5
  - tensorflow=2.14.0
  - scikit-learn
  - scipy
  - matplotlib
  - notebook
  - jupyter
  - streamlit
  - tqdm
  - pip
  - pip:
      - lightfm
